### ISSUE TITLE
Remove chesire from runtime dependencies

### ISSUE THREAD

**Issue by kennyjwilli** [xapix-io/axel-f#86] opened 2019-11-19 23:31 UTC
Cheshire is currently a runtime dependency of axel-f. It is only used in the namespace `axel-f.excel.json`. Because Cheshire is such a massive dependency, bringing in Jackson, it'd be great to make it optional. If a user requires the `axel-f.excel.json` namespace, they will need to have cheshire on their classpath.

**Comment by kennyjwilli** [comment] 2019-11-19 23:35
Looks like the change would be as simple as removing [this line](https://github.com/xapix-io/axel-f/blob/714f8762be02be395e807c758f40834cc4e9912c/src/axel_f/excel.cljc#L13) and notifying users to explicitly add that require if they want the JSON functions imported.

**Comment by DeLaGuardo** [comment] 2019-11-20 12:03
This is not that simple right now. `axel-f.excel` namespace depends on `axel-f.excel.json` because of `env` variable that needs to have all the dependencies in one place. Here lies the root cause of the problem - `compile` function can not work without `axel-f.excel/env`. How about a different solution: 
  * cheshire can be excluded from runtime dependencies by library consumer.
  * `axel-f.excel/compile` function will be separated from the `axel-f.excel/env` by adding one more argument that should provide a map with internal functions.
  * dependencies could be separated into `core` (no extra dependencies needed) and `json, ...` where each will require their one dependencies

What do you think?

**Comment by kennyjwilli** [comment] 2019-11-20 17:11
Are those 3 different suggestions or 3 steps for 1 implementation? 

> `axel-f.excel/compile` function will be separated from the `axel-f.excel/env` by adding one more argument that should provide a map with internal functions.

Is there a reason you need to identify internal functions? If not, it seems like the json functions could already be passed to the `compile` function via the [`extra-env` parameter](https://github.com/xapix-io/axel-f/blob/714f8762be02be395e807c758f40834cc4e9912c/src/axel_f/excel.cljc#L53).

> dependencies could be separated into `core` (no extra dependencies needed) and `json, ...` where each will require their one dependencies
I'm not totally following this.

**Comment by kennyjwilli** [comment] 2020-01-26 00:09
In the latest version, this same issue applies but for both `org.bouncycastle/bcprov-jdk15on` and `org.bouncycastle/bcpkix-jdk15on`. We don't want these deps brought into our project & exclusions result in 
```
Syntax error (ClassNotFoundException) compiling at (axel_f/buddy/hash.cljc:1:1).
org.bouncycastle.crypto.Digest
```

I love the idea of having lots of these extra helper packages for specific use cases! The dependencies for these helper packages should be optional though.

**Comment by DeLaGuardo** [comment] 2020-01-27 10:17
I created #90 to help you remove extra dependencies. It has axel-f.excel-lite namespace that can be used as a drop in replacement for axel-f.excel. But it loading only helpers without extra dependencies. Also I added axel-f.runtime namespace to build your own wet of runtime helpers. Please check axel-f.excel and excel-lite to understand how to use it. 

snapshoted 2.0.12-SNAPSHOT will be released soon so you can give it a try and please tell me how it fits into your workflow.

Cheers)

**Comment by DeLaGuardo** [comment] 2020-01-27 10:22
![image](https://user-images.githubusercontent.com/542042/73166972-41027000-40f7-11ea-9bf9-891088986c7f.png)

The quickest way to try:
```
clj -Sdeps '{:deps {io.xapix/axel-f {:mvn/version "2.0.12-SNAPSHOT" :exclusions [cheshire clojure.java-time org.bouncycastle/bcprov-jdk15on org.bouncycastle/bcpkix-jdk15on commons-codec/commons-codec]}}}'
```

**Closed** 2020-01-31 09:27 UTC
